powerhouse-inc/effective-octo-adventure

- editors/atlas-multi-parent-editor/editor.tsx
- Should Unified and Edit options be hardcoded
- Should the data be populated
> feat(atlas): save data as came from state and use new callback funtions

- editors/shared/components/content-card.tsx
- editors/shared/components/tags-status.tsx
- editors/shared/utils/utils.ts
Unified/Edit-> tag should be “Edition Atlas”
> feat(atalas): add new tag for editions

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-exploratory-editor/editor.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-foundation-editor/editor.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-grounding-editor/editor.tsx
https://trello.com/c/TYC1u6Dl/937-unified-view-edit-mode-for-atlas-foundational-and-grounding-documents
- PHID: Should show the correct option preview when have initial value. (Foundation & Grounding forms)
- PHID: Should save the correct value. (Foundation & Grounding forms)
> fix: initial option & save in PHID field

- editors/atlas-foundation-editor/editor.tsx
- editors/atlas-grounding-editor/editor.tsx
- editors/shared/utils/utils.ts
https://trello.com/c/TYC1u6Dl/937-unified-view-edit-mode-for-atlas-foundational-and-grounding-documents
- Should allow empty in not required String fields
> fix: allow empty in not required String fields (Foundation & Grounding forms)

- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- Should display a split view with two panels: an editable panel on the left and a read-only diff comparison panel on the right. (Grounding)
- Should the left panel allow to edit the fields for each section (title, ID, body texts, tags, etc). (Grounding)
- Should the right panel show the recent changes highlight differences: Red highlights for deletions, Green highlights for additions or modifications. (Grounding, in progress)
- Should the Status in the Diff panel show the previous and the new status. If new status-> also show it in the diff panel. (Grounding)
- Should the Edits made in this view be captured as document operations and logged in the revision history. (Grounding)
- Should the …
> feat: add diff fields to Grounding form & preserve the originalNodeState between renders

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
- Content label should not be displayed (all documents)
> fix(atlas): remove all label content

- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/shared/components/SplitView.tsx
- Should update remaining baseline values (in progress)
- Tags component is not visible in the Split view
- Tags component-> multiple items selected, the component increases its width. 
- PHID component-> long title, the component increases its width.
> fix: add more baseline values & fix issues in Foundation & Grounding forms

- document-models/atlas-foundation/src/reducers/context.ts
- document-models/atlas-foundation/src/reducers/general.ts
https://trello.com/c/9d8FMTjw
- Atlas references field-> adding a phd, clearing the data and selecting a new one, when click outside of the field, the old phid is displayed.
> fix(atlas): fix the reference and context for PHID

- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
-  Should the the text not over overflow the input, instead truncate
> fix(atlas): truncate text for grounding and foundations docs

- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-foundation-editor/editor.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-grounding-editor/editor.tsx
- editors/shared/components/diff-fields/phid-diff-field.tsx
- editors/shared/utils/utils.ts
- PHID: In the diff comparison  a "-" is displayed as part of the differences.
- PHID: In the diff comparison, the protocol should not be included because this info is not coming from the data at this moment.
- Textarea (content section): the field displays only a part of the content while from the data is coming additional info for this field.
> fix: Content & Parent logic issues in Foundation & Grounding forms

- editors/drive-explorer/components/EditorContainer.tsx
- editors/shared/components/EditorLayout.tsx
- editors/shared/context/view-mode-context.tsx
- Split view. Go to the history and get back to the forms. The split view, the current view where you was before go to the history, should be displayed
> fix: show the correct view mode after close the revision history

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/shared/components/forms/generics/GenericPHIDForm.tsx
- PHID: clicking on the refresh icon, the data should be reloaded and saved if changed (Single PHID-based fields)
> feat: save data if changed when clicking on the refetch icon in single PHID-based fields

- editors/shared/components/forms/MultiPhIdForm.tsx
- PHID: clicking on the refresh icon, the data should be reloaded and saved if changed (Multi PHID based fields)
> feat: save data if changed when clicking on the refetch icon in multi PHID based fields

- editors/shared/components/forms/MultiPhIdForm.tsx
- editors/shared/components/forms/generics/GenericPHIDForm.tsx
- PHID: clicking on the refresh icon, the data should be reloaded and saved if changed (All PHID based fields)
> fix: avoid to remove data when refetch in PHID-based fields

- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
- editors/atlas-scope-editor/components/ScopeForm.tsx
- editors/atlas-scope-editor/editor.tsx
- From the history view, going back to the form, the Content section is visible after a few seconds causing the PHDs section to jump up and down.
> fix(atlas): add min-height to avoid jump

- style.css
https://trello.com/c/2LUrNgnQ/994-release-to-staging-atlas-dmeditor-05-05-25
This relative .css import fails because the .css files don't get moved to the /dist folder on pnpm build.
> fix(atlas): add makdonw styles in root file

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-scope-editor/components/ScopeForm.tsx
- editors/atlas-set-editor/components/SetForm.tsx
https://trello.com/c/X10a3hCg/989-add-the-read-only-diff-status-for-the-strings-to-the-document-types
- Foundation doc. Name field. Removing the name value. **Expected Output:** The field should allow empty values. **Current Output:** The "Expected string, received null" error message appears above the field.
> fix(atlas): fix the null values in name mandatory field

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-exploratory-editor/editor.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-foundation-editor/editor.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-grounding-editor/editor.tsx
- editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
- editors/atlas-multi-parent-editor/editor.tsx
- editors/atlas-scope-editor/components/ScopeForm.tsx
- editors/atlas-scope-editor/editor.tsx
- editors/atlas-set-editor/components/SetForm.tsx
- editors/atlas-set-editor/editor.tsx
- editors/shared/components/diff-fields/enum-diff-field.tsx
- editors/shared/components/diff-fields/string-diff-field.tsx
- editors/shared/components/diff-fields/url-diff-field.tsx
- editors/shared/components/diff-text.tsx
- editors/shared/components/forms/MultiPhIdForm.tsx
- editors/shared/components/forms/generics/GenericPHIDForm.tsx
- editors/shared/components/forms/generics/GenericTextForm.tsx
- editors/shared/providers/FormModeProvider.tsx
- editors/shared/types.ts
- editors/shared/utils/utils.ts
https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
Should add the read only diff status in the Split/Edit
> fix(atlas): add same type in all form

- editors/atlas-exploratory-editor/components/AdditionalGuidance.tsx
- editors/shared/components/field-skeleton.tsx
- editors/shared/components/forms/DocNameForm.tsx
- editors/shared/components/forms/DocNoForm.tsx
- editors/shared/components/forms/DocTypeForm.tsx
- editors/shared/components/forms/GlobalTagsForm.tsx
- editors/shared/components/forms/MarkdownContentForm.tsx
- editors/shared/components/forms/MasterStatusForm.tsx
- editors/shared/components/forms/MultiPhIdForm.tsx
- editors/shared/components/forms/MultiUrlForm.tsx
- editors/shared/components/forms/SinglePhIdForm.tsx
- editors/shared/components/ui/skeleton.tsx
https://trello.com/c/MPhuo91G/1080-keep-the-toggle-selection-after-changing-the-document-in-the-sidebar
- Replace labels by a skeleton when loading the base document to show the differences
> fix: replace labels by a skeleton when loading the base document

- editors/atlas-scope-editor/editor.tsx
- https://trello.com/c/VxEAOY5z/1109-change-the-title-of-the-scope-documents-to-atlas-scope
- Should change the "Atlas Explorer - The Support Scope" doc type to "Atlas Scope" only for the scope documents.
> fix(atlas): fix the name of scope documents

- editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
- https://trello.com/c/Fu7AV5Jc/1105-multiparent-document-is-created-with-null-when-no-doc-number-is-provided
- Multiparent document, parent document already inserted. Changing the parent document.  **Expected Output:** The multiparent node should be moved to the new parent node and take the proper document number. **Current Output:** The multiparent node is moved to the proper place, but the document number is displayed as Null; it is not taking the parent document number.  Update the DocNumber when update the parent in the docs
> fix(atlas): add docNo in the update operation

- editors/drive-explorer/sidebar-utils.ts
- editors/shared/components/forms/generics/GenericPHIDForm.tsx
- https://trello.com/c/4QykDyTJ/1111-multiparent-document-is-displayed-with-the-name-undefined-in-the-sidebar
- Should the multi-parent node be created by default with the placeholder: Name. When create a new multi-parent document,  this placeholder should be show
> fix(scalars): fix the issue generic phID add same placeholder all docs

- editors/shared/components/ArrayField.tsx
- editors/shared/components/toggle-switch.tsx
- eslint.config.js
- https://trello.com/c/0c0YJofT/1113-cannot-read-properties-of-undefined-reading-value-error-appears-after-changing-a-parent-document
-  Should ensure that the update in the parent documents is applied properly. 
- Ensure that updates to the parent documents are applied correctly.
- On submit, the form is trying to process IDs of fields that have already been deleted.
> fix(atlas): remove the ! condition and get fields as source of true

- editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
- editors/atlas-foundation-editor/components/FoundationForm.tsx
- editors/atlas-grounding-editor/components/GroundingForm.tsx
- editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
- editors/atlas-set-editor/components/SetForm.tsx
- editors/shared/hooks/useParentOptions.ts
https://trello.com/c/AWOgrthv/1144-documents-cant-be-their-own-parent
- Should ensure that in the parent documents list, the own PHID document is not listed
> fix: exclude the current document from its parent list in PHID-based fields

- editors/drive-explorer/sidebar-utils.ts
https://trello.com/c/ifPlHVoe/1154-set-document-should-not-be-created-in-the-sidebar-with-doc-no-placeholder
- Should ensure that the Set document type doesn't show Doc No in the node tree.
> fix(atlas): set document should no have number
