powerhouse-inc/effective-octo-adventure

document-models/atlas-scope/src/reducers/context.ts
editors/atlas-scope-editor/components/TagsStatus.tsx
editors/atlas-scope-editor/components/ToggleSwitch.tsx
editors/atlas-scope-editor/editor.tsx

- Should create a form with the latest version of the document.
- Should the form allow to edit the fields for each section (title, ID, bode texts, tags, etc)

feat(scalars): add the component of powerhouse to unified view

---

editors/atlas-scope-editor/components/SetContentForm.tsx
editors/atlas-scope-editor/components/SetDocNumberForm.tsx
editors/atlas-scope-editor/components/SetMasterStatusForm.tsx
editors/atlas-scope-editor/components/SetOriginalContextData.tsx
editors/atlas-scope-editor/components/SetProvenanceFrom.tsx
editors/atlas-scope-editor/components/SetTagsForm.tsx
editors/atlas-scope-editor/editor.tsx

-  Should no diff highlights (additions/removals) or change history should be visible in this mode.

fix(atlas): fix the onchange in the tags

---

editors/atlas-scope-editor/editor.tsx
editors/share/components/toggle-switch.tsx

Should hide Toggles . Hardcode: Unified, Edit

fix(scalars): hard code unified and edit

---

editors/atlas-multi-parent-editor/editor.tsx
editors/atlas-scope-editor/editor.tsx
editors/share/components/Layout.tsx
editors/share/components/utils/utils.ts

- Should create a form with the latest version of the document.

fix(atlas): Add scaffolding for multiparent form

---

.vscode/settings.json
editors/atlas-grounding-editor/editor.tsx
editors/shared/components/utils/utils.ts

https://trello.com/c/TYC1u6Dl/937-unified-view-edit-mode-for-atlas-foundational-and-grounding-documents
- Should create a form with the latest version of the document (Grounding form)
- Should the data be populated (in progress)
- Should Unified and Edit options be hard-coded (Grounding form)
- Should the form allow to edit the fields for each section (title, id, texts, tags, etc) (Grounding form)

feat: update grounding editor & shared utils

---

editors/atlas-multi-parent-editor/editor.tsx

- Should the form allow to edit the fields for each section (title, ID, bode texts, tags, etc)

feat(atalas): add state for each field

---

editors/atlas-scope-editor/editor.tsx

- Should the form allow to edit the fields for each section (title, ID, bode texts, tags, etc)

fix(scalars): move all field into single form

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-exploratory-editor/editor.tsx
editors/atlas-grounding-editor/editor.tsx
editors/atlas-multi-parent-editor/editor.tsx
editors/atlas-scope-editor/editor.tsx
editors/drive-explorer/components/driver-layout.tsx
editors/drive-explorer/editor.tsx
editors/shared/components/EditorLayout.tsx
editors/shared/components/SplitView.tsx
editors/shared/utils/utils.ts
vite-env.d.ts

https://trello.com/c/9d8FMTjw
- Created editor layout to reuse logic and ui components

feat: created editor layout

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-multi-parent-editor/editor.tsx
editors/shared/components/toggle-switch.tsx
editors/shared/utils/utils.ts

- Should the editor allow to save drafts.
- Should the editor validate required fields before submission.

fix(atlas): add new form component and add utils functions

---

editors/atlas-grounding-editor/editor.tsx
eslint.config.js
package.json
pnpm-lock.yaml

https://trello.com/c/TYC1u6Dl/937-unified-view-edit-mode-for-atlas-foundational-and-grounding-documents
- Should the editor validate required fields before submission (Grounding form)
- Should the editor allow to save drafts (Grounding form)

feat: save edited data onBlur & onChange

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-scope-editor/editor.tsx

fix(atlas): use the reusable form and fix some size

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx

-Update the form and fix the parents field

feat(atlas): fix the parent field and use new function

---

editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/shared/components/diff-fields/enum-diff-field.tsx
editors/shared/components/diff-fields/fake-input.tsx
editors/shared/components/diff-fields/string-diff-field.tsx
editors/shared/components/diff-text.tsx
editors/shared/types.ts

- improve types
- improve doc view
- created mechanism to show efficiently the differences between the documents

feat: show foundation differences

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-exploratory-editor/editor.tsx
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-foundation-editor/editor.tsx
editors/shared/components/diff-fields/fake-input.tsx
editors/shared/components/diff-fields/string-diff-field.tsx
editors/shared/components/diff-fields/url-diff-field.tsx
editors/shared/components/diff-text.tsx
editors/shared/utils/common-options.ts

https://trello.com/c/zGM3ZHxc
- improve exploratory documents
- add differences for exploratory docs
- add support for url diff fields
- added multiline capabilities to the strings diff fields
- improve component reusability

feat: add diff fields to the exploratory documents

---

style.css

Ticket
- https://trello.com/c/iatpFQ28/933-unified-view-edit-mode-for-no-parent-document-types
Description
- Optional field/Error message in black

fix(atlas): fix the errors colors

---

editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-scope-editor/editor.tsx

Ticket
Description
- Use the reusable component in the Scope form

feat(atlas) add the same components to scope form

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-multi-parent-editor/editor.tsx
editors/atlas-scope-editor/editor.tsx
editors/shared/utils/utils.ts

- Should fix error, expect string and got null

fix(atlas): fix issue-expect string recive null

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-exploratory-editor/editor.tsx

- improve exploratory document ui
- display icons correctly in the provenance URL field

feat: improve exploratory ui

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-multi-parent-editor/editor.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-scope-editor/editor.tsx

- Add new change in the multi-parent documents

fix(atlas): add new change in multiparent document

---

document-models/atlas-scope/src/reducers/tags.ts

feat(atlas): implement reducer scope tags

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-exploratory-editor/editor.tsx

- Should change the layout with the new design

feat(atlas): add new field and modified the layout

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx

- Should update the Findings section

feat(atlas): add new layout for multiparent and scope

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/shared/components/diff-fields/phid-diff-field.tsx

- PHID. Update the variant to "withValueAndTitle"

fix: update PHID field variant in all forms

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-exploratory-editor/editor.tsx
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-foundation-editor/editor.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/atlas-grounding-editor/editor.tsx
editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-multi-parent-editor/editor.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-scope-editor/editor.tsx

Ticket
Description
- Should update the Findings section

feat(atlas): add layout split for all documents

---

editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/shared/components/diff-fields/phid-diff-field.tsx
editors/shared/components/diff-text.tsx

fix: improve styles

---

document-models/atlas-foundation/src/reducers/context.ts
document-models/atlas-foundation/src/reducers/general.ts
document-models/atlas-grounding/src/reducers/context.ts
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-foundation-editor/editor.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/atlas-grounding-editor/editor.tsx

fix: logic issues

---

editors/atlas-foundation-editor/editor.tsx
editors/atlas-grounding-editor/editor.tsx
editors/shared/components/diff-fields/phid-diff-field.tsx

- Diff comparison functionality (improve)

fix: improve logic of Parent PHID

---

editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-foundation-editor/editor.tsx
editors/shared/components/forms/GlobalTagsForm.tsx
editors/shared/components/forms/MasterStatusForm.tsx
editors/shared/components/forms/generics/GenericEnumForm.tsx

https://trello.com/c/9d8FMTjw
- migrate global tags in the foundation document

refactor: migrate foundation global tags

---

editors/shared/components/diff-text.tsx

fix(atlas): fix the diff colors component

---

editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-scope-editor/components/SetTagsForm.tsx

- Apply the latest fixes in Scope doc from the following(PR: https://github.com/powerhouse-inc/effective-octo-adventure/pull/83)

fix(atlas): apply the last change in PHID in scope

---

editors/drive-explorer/components/types.ts
scripts/apply-changes.ts
scripts/apply-changes/AtlasFoundationClient.ts
scripts/apply-changes/AtlasScopeClient.ts
scripts/apply-changes/atlas-base/utils.ts

https://trello.com/c/1OWcwLJ0
- Fix remaining issues in the `apply-changes` script

fix: apply-change script issues

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/shared/components/forms/generics/GenericEnumForm.tsx

- Apply the necessary changes after schema update->Multiparent document

fix(atlas): add the last change in multiparents

---

editors/atlas-multi-parent-editor/components/MultiparentForm.tsx

- Apply the latest fixes in Multiparent doc from the following

fix(atlas): fix the multiparent duplicate add elements

---

editors/shared/components/ArrayField.tsx

- PHID (Array): saving PHIDs with the same value should not be allowed and an error message should always be displayed in this case

fix: submit logic in ArrayField component

---

editors/shared/components/forms/MultiPhIdForm.tsx

- Should fix the jumping issue in PHID info

fix: jumping issue in PHID info

---

scripts/apply-changes/clients/AtlasExploratoryClient.ts
subgraphs/atlas-exploratory/resolvers.ts
subgraphs/atlas-feedback-issues/resolvers.ts
subgraphs/atlas-foundation/resolvers.ts
subgraphs/atlas-grounding/resolvers.ts
subgraphs/atlas-multi-parent/resolvers.ts
subgraphs/atlas-multiparent/resolvers.ts
subgraphs/atlas-scope/resolvers.ts
subgraphs/atlas-set/resolvers.ts

https://trello.com/c/2LUrNgnQ/994-release-to-staging-atlas-dmeditor-05-05-25
- Should deploy to Staging the latest change of the Atlas DM+Editor (Unified/Edit)

fix(atlas): fix error in type resolvers and fix type AtlasExploratory

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/shared/utils/utils.ts
package.json
pnpm-lock.yaml

https://trello.com/c/wAmbLyTg/1004-add-the-boolean-read-only-diff-status-to-the-document-types
Should add the read only diff status in the Unified/Read Only

fix(scalars): pass the mixed in the toogle and apply to exploratory

---

document-models/utils.ts
editors/shared/hooks/useDocumentsLink.ts
scripts/apply-changes.ts
scripts/apply-changes/atlas-base/utils.ts
scripts/apply-changes/clients/AtlasExploratoryClient.ts
scripts/apply-changes/clients/AtlasFoundationClient.ts
scripts/apply-changes/clients/AtlasGroundingClient.ts
scripts/apply-changes/clients/AtlasMultiParentClient.ts
scripts/apply-changes/clients/AtlasSetClient.ts

https://trello.com/c/qbXxNzFX/1010-after-a-forking-a-scope-child-nodes-in-sidebar-are-not-placed-according-to-explorers-hierarchy
- Add the parent object in the import script correctly
- Improve code

fix: exploratory parents

---

editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/shared/components/forms/MarkdownContentForm.tsx

https://trello.com/c/uIehRvcV
- Show the content as read-only differences

feat: show content differences

---

scripts/apply-changes/atlas-base/utils.ts
scripts/apply-changes/clients/AtlasExploratoryClient.ts
scripts/apply-changes/clients/AtlasFoundationClient.ts
scripts/apply-changes/clients/AtlasGroundingClient.ts
scripts/apply-changes/clients/AtlasMultiParentClient.ts
scripts/apply-changes/clients/AtlasScopeClient.ts

https://trello.com/c/opniEnpF
- Convert the original context data in the import script to URLs to notion

feat: convert context data ids to url in the import script

---

editors/drive-explorer/components/driver-layout.tsx
editors/drive-explorer/sidebar-utils.ts

https://trello.com/c/opniEnpF
- sidebar nodes smart sort, recognizing correctly doc numbers and agent doc numbers

feat: sort sidebar nodes

---

editors/shared/hooks/useDocumentsLink.ts

https://trello.com/c/uEs5oGtC/1044-fix-connect-issue-in-effecttive-octo-repo
- Should fix the issue

fix: context issue outside atlas driver

---

document-models/utils.ts
editors/atlas-exploratory-editor/components/ExploratoryForm.tsx
editors/atlas-foundation-editor/components/FoundationForm.tsx
editors/atlas-grounding-editor/components/GroundingForm.tsx
editors/atlas-multi-parent-editor/components/MultiparentForm.tsx
editors/atlas-scope-editor/components/ScopeForm.tsx
editors/atlas-set-editor/components/SetForm.tsx
editors/shared/components/forms/MultiPhIdForm.tsx
editors/shared/components/forms/MultiUrlForm.tsx

https://trello.com/c/Lmk62TFZ/992-update-remaining-baselines-values-for-the-splits-view
- Should update the baseline values (Grounding, Exploratory, Multiparent, Scope & Set docs)

feat: update the baseline values in Grounding, Exploratory, Multiparent, Scope & Set docs

---

editors/shared/components/forms/MultiPhIdForm.tsx
editors/shared/components/forms/generics/GenericPHIDForm.tsx
editors/shared/hooks/useParentOptions.ts
editors/shared/utils/phids.ts
editors/shared/utils/utils.ts

https://trello.com/c/rReZP17X/1049-update-phid-component-to-load-data-properly
- Update fetchSelectedOptionCallback logic in PHID based fields
- Remove unused code

fix: update fetchSelectedOptionCallback logic in PHID based fields & remove unused code

---

editors/drive-explorer/components/driver-layout.tsx

https://trello.com/c/agHwHnX2/1076-atlas-sidebar-cant-be-resized-properly-in-connect
- Should allow to resize the sidebar

fix: sidebar resize issue

---

editors/drive-explorer/sidebar-utils.ts

https://trello.com/c/VoYBUfLa/1074-import-the-multiparent-documents-properly
- Should fix the title in the Sidebar for multi-parents documents

fix: title in the Sidebar for multi-parents documents

---

editors/drive-explorer/sidebar-utils.ts
package.json
pnpm-lock.yaml

- https://trello.com/c/8TO462mo/1112-document-types-created-are-represented-with
##Description
- Should ensure that the node is by default created with the placeholder: Doc No - Name 
ScreenShot

fix(scalars): add placeholder and italic documnet without docNo and name
